config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :skills
  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to clients_path, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email, :phone, :fiscal_number, :website, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@skills = Skill.all
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
    @skill = Skill.new
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to skills_path, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        @skills = Skill.all
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to skills_path, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:title, :icon, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/clients/_form.html.erb
<%= form_for(client) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name...' %>
  </div>

    <div class="form-group">
    <%= f.text_field :email, class: 'form-control', placeholder: 'Email...' %>
  </div>

    <div class="form-group">
    <%= f.text_field :phone, class: 'form-control', placeholder: 'Phone number...' %>
  </div>

    <div class="form-group">
    <%= f.text_field :fiscal_number, class: 'form-control', placeholder: 'Fiscal number...' %>
  </div>

    <div class="form-group">
    <%= f.text_field :website, class: 'form-control', placeholder: 'Website...' %>
  </div>

    <div class="form-group">
    <%= f.text_field :address, class: 'form-control', placeholder: 'Address...' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary pull-right' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
        </div>
      </div>
      <div class="row">
          <!-- TABLE: LATEST ORDERS -->
          <div class="col-md-3"></div> 
          <div class="col-md-6"> 
            <div class="">
              <div class="box box-info">
                <div class="box-header with-border">
                  <h3 class="box-title">Editing Skill</h3>

                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  <div class="table-responsive">                    
          					<%= render 'form', client: @client %>
                    <%= link_to 'Back', clients_path, class: 'btn btn-default' %>
                  </div>
                  <!-- /.table-responsive -->
                </div>

                <!-- /.box-footer -->
              </div>
            </div>
          </div>
          <div class="col-md-3"></div>
        </div>
      </div>
    </section>

app/views/clients/index.html.erb
  <div class="content-wrapper">
    <section class="content-header">
    </section>
    <section class="content">
      <div class="row">
        <div class="col-md-12">
        </div>
      </div>
      <div class="row">
          <!-- TABLE: LATEST ORDERS -->
          <div class="col-md-12"> 
            <div class="">
              <div class="box box-info">
                <div class="box-header with-border">
                  <h3 class="box-title">Clients</h3>

                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  <div class="table-responsive">

        <p id="notice"><%= notice %></p>
        <table class="table table-striped">
            <tbody>
              <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Fiscal Number</th>
                  <th>Website</th>
                  <th></th>
                </tr>
                <% @clients.each do |client| %>
                <tr>
                  <td><%= client.name %></td>
                  <td><%= client.email %></td>
                  <td><%= client.phone %></td>
                  <td><%= client.fiscal_number %></span></td>
                  <td><%= client.website %></td>
                  <th class="text-center">
                    <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_client_path(client), class: 'btn btn-warning btn-xs' %>
                    <%= link_to "<i class='fa fa-trash'></i>".html_safe, client, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>                  
                  </th>
                </tr>
                <% end %>
              </tbody>
            </table>
                  <br>

               <%= link_to 'New client', new_client_path, class: 'btn btn-primary' %>
 
              </div>
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    </section>

app/views/clients/new.html.erb
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
        </div>
      </div>
      <div class="row">
          <!-- TABLE: LATEST ORDERS -->
          <div class="col-md-3"></div> 
          <div class="col-md-6"> 
            <div class="">
              <div class="box box-info">
                <div class="box-header with-border">
                  <h3 class="box-title">New Skill</h3>

                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  <div class="table-responsive">                    
          					<%= render 'form', client: @client %>
                    <%= link_to 'Back', clients_path, class: 'btn btn-default' %>
                  </div>
                  <!-- /.table-responsive -->
                </div>

                <!-- /.box-footer -->
              </div>
            </div>
          </div>
          <div class="col-md-3"></div>
        </div>
      </div>
    </section>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Fiscal number:</strong>
  <%= @client.fiscal_number %>
</p>

<p>
  <strong>Website:</strong>
  <%= @client.website %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  	<title>Workflow</title>
	    <meta charset="utf-8">
		  <meta http-equiv="X-UA-Compatible" content="IE=edge">
		  <title>UTU | Home</title>
		  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
		  <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
		  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
		  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
		  <link rel="stylesheet" href="plugins/jvectormap/jquery-jvectormap-1.2.2.css">
		  <link rel="stylesheet" href="dist/css/AdminLTE.min.css">
		  <link rel="stylesheet" href="dist/css/skins/_all-skins.min.css">
		    <%= csrf_meta_tags %>
        <%= favicon_link_tag 'favicon.ico' %>
		    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body class="hold-transition skin-black sidebar-mini">
		<div class="wrapper">

  <header class="main-header">

    <!-- Logo -->
   <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">
        <%= image_tag("logo.png", :alt => "rss feed", :height => '30px') %>
      </span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">
        <%= image_tag("logo.png", :alt => "rss feed", :height => '50x') %>
      </span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          
          <!-- Notifications: style can be found in dropdown.less -->
          
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs">Alexander Pierce</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                  <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Edit Profile</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
               </li>
                </p>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
        </ul>
      </div>

    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->

      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">ADMIN PANEL</li>
        <li class="<%= current_page?(home_index_path) ? 'active treeview' : '' %>">
          <%= link_to '<i class="fa fa-dashboard-o"></i> Home'.html_safe, home_index_path, class: '' %>
        </li>
        <li class="treeview">
          <a href="pages/projects/index.html">
            <i class="fa fa-clone"></i> <span>Projects</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><%= link_to '<i class="fa fa-circle-o"></i> Clients'.html_safe, clients_path, class: '' %></li>
            <li><a href="pages/projects/management.html"><i class="fa fa-circle-o"></i> Management</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-group"></i> <span>Team</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview treeview-menu">
            <li><a href="pages/team/accounts.html"><i class="fa fa-circle-o"></i> Accounts</a></li>
            <li><a href="pages/team/creatives.html"><i class="fa fa-circle-o"></i> Creatives</a></li>
            <li><%= link_to '<i class="fa fa-circle-o"></i> Skills'.html_safe, skills_path, class: '' %></li>
          </ul>
        </li>

      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

    <%= yield %>
    	
    	    <!-- /.content -->
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <p>&copy; 2017 Workflow - Empowering People.</p>
  </footer>

  </div>
   <div class="control-sidebar-bg"></div>
  </div>





<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false
    });
  });
  </script>
  <script>
  $(function () {
    $(".select2").select2();
    $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
    $("#datemask2").inputmask("mm/dd/yyyy", {"placeholder": "mm/dd/yyyy"});
    $("[data-mask]").inputmask();
    $('#reservation').daterangepicker();
    $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A'});
    $('#daterange-btn').daterangepicker(
        {
          ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Last 7 Days': [moment().subtract(6, 'days'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
          },
          startDate: moment().subtract(29, 'days'),
          endDate: moment()
        },
        function (start, end) {
          $('#daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        }
    );
    $('#datepicker').datepicker({
      autoclose: true
    });
    $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
      checkboxClass: 'icheckbox_minimal-blue',
      radioClass: 'iradio_minimal-blue'
    });
    $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
      checkboxClass: 'icheckbox_minimal-red',
      radioClass: 'iradio_minimal-red'
    });
    $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
      checkboxClass: 'icheckbox_flat-green',
      radioClass: 'iradio_flat-green'
    });
    $(".my-colorpicker1").colorpicker();
    $(".my-colorpicker2").colorpicker();
    $(".timepicker").timepicker({
      showInputs: false
    });
  });
</script>


<script src="plugins/jQuery/jquery-2.2.3.min.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>
<script src="plugins/fastclick/fastclick.js"></script>
<script src="dist/js/app.min.js"></script>
<script src="plugins/sparkline/jquery.sparkline.min.js"></script>
<script src="plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="plugins/slimScroll/jquery.slimscroll.min.js"></script>
<script src="plugins/chartjs/Chart.min.js"></script>
<script src="dist/js/pages/dashboard2.js"></script>
<script src="dist/js/demo.js"></script>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="plugins/morris/morris.min.js"></script>
<script src="plugins/sparkline/jquery.sparkline.min.js"></script>
<script src="plugins/knob/jquery.knob.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="plugins/daterangepicker/daterangepicker.js"></script>
<script src="plugins/datepicker/bootstrap-datepicker.js"></script>
<script src="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script src="plugins/datatables/jquery.dataTables.min.js"></script>
<script src="plugins/datatables/dataTables.bootstrap.min.js"></script>



	</body>
</html>

app/views/skills/_form.html.erb
<%= form_for(skill) do |f| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: 'Skill title...' %>
  </div>

  <div class="form-group">
    <%= f.text_field :icon, class: 'form-control', placeholder: 'Skill title...' %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, class: 'form-control', placeholder: 'Description...' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save changes', class: 'btn btn-primary pull-right' %>
  </div>
<% end %>

app/views/skills/edit.html.erb
  <div class="content-wrapper">
  <!--
    <section class="content-header">
      <h1>
        <small>Skill</small>
      </h1>
      <ol class="breadcrumb">
        <li><i class="fa fa-dashboard active"></i> Home</li>
      </ol>
    </section>
-->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
        </div>
      </div>
      <div class="row">
          <!-- TABLE: LATEST ORDERS -->
          <div class="col-md-3"></div> 
          <div class="col-md-6"> 
            <div class="">
              <div class="box box-info">
                <div class="box-header with-border">
                  <h3 class="box-title">Editing Skill</h3>

                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  <div class="table-responsive">                    
          					<%= render 'form', skill: @skill %>
          					<%= link_to 'Back', skills_path, class: 'btn btn-default' %>
                  </div>
                  <!-- /.table-responsive -->
                </div>

                <!-- /.box-footer -->
              </div>
            </div>
          </div>
          <div class="col-md-3"></div>
        </div>
      </div>
    </section>

app/views/skills/index.html.erb
  <div class="content-wrapper">
    <section class="content-header">
    </section>
    <section class="content">
      <div class="row">
        <div class="col-md-12">
        </div>
      </div>
      <div class="row">
          <!-- TABLE: LATEST ORDERS -->
          <div class="col-md-8"> 
            <div class="">
              <div class="box box-info">
                <div class="box-header with-border">
                  <h3 class="box-title">Skills</h3>

                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  <div class="table-responsive">
                  <p id="notice"><%= notice %></p>
                    <table class="table no-margin">
                      <thead>
                      <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Description</th>
                        <td colspan="2"></td>
                      </tr>
                      </thead>
                      <tbody>
                      <% @skills.each do |skill| %>
                      <tr>
                        <td><i class="<%= skill.icon %>"></i></td>
                        <td><%= skill.title %></td>
                        <td><%= skill.description %></td>
                        <td>
                        <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_skill_path(skill), class: 'btn btn-warning btn-xs' %>
                        <%= link_to "<i class='fa fa-trash'></i>".html_safe, skill, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %> 
                        </td>
                      </tr>
                      <% end %>

                      </tbody>
                    </table>
                  </div>
                  <!-- /.table-responsive -->
                </div>

                <!-- /.box-footer -->
              </div>
            </div>
          </div>
          <div class="col-md-4">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">New Skill</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                <%= form_for @skill, url: { controller: "skills", acction: "create" } do |form| %>
                 <div class="form-group">
                 <%= form.text_field :title, class: 'form-control', placeholder: 'Skill title...' %>
                 </div>

                 <div class="form-group">
                  <%= form.text_field :icon, class: 'form-control', placeholder: 'Icon code...' %>
                 </div>

                 <div class="form-group">
                  <%= form.text_area :description, class: 'form-control', placeholder: 'Description...' %>
                 </div>

                 <div class="form-group">
                  <%= form.submit 'Create new skill', class: 'btn btn-block btn-primary' %>
                 </div>
               <% end %>
              </div>
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    </section>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @skill.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @skill.description %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>